# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kaleb Ruscitti
description: "I do math kind of."
baseurl: "" # the subpath of your site, e.g. /blog
url:  "kaleb.ruscitti.ca" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  math_engine: katex
# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: standard  # choices are: 'dark', 'standard', 'markdown'

# Customizations
email: kaleb@ruscitti.ca

navigation:
  - text: Home
    url: /
  - text: Curriculum Vitae
    url: /resume
  - text: Writing
    url: /articles
  - text: Contact
    url: /contact
  - text: Collection
    url: /links

projects:
  - name: Adaptive Optics for Addressing Ions in an Ion Trap.
    description: We implement adaptive optics in a laboratory setting with the goal of gaining optical abberation correction and detailed, in-situ and real-time addressing of ions in a Yb+ ion trap.
    link: https://github.com/QITI/pySLM
  - name: Math Animations
    description: A series of small math animations I made to capture some interesting and beautiful concepts in mathematics.
    link: https://github.com/kalebruscitti/Small-Animations
    image:
  - name: Pygame Gravity Visualization
    description: A 2D Simulation/Visualization of Newtonian gravitation, using python 2.7 and the pygame library. One of my very first programming projects.
    link: https://github.com/kalebruscitti/GravitySimulation
    image:

social:

# Plugins
plugins:
  - jekyll-seo-tag
